site_name: Documentation de Riff

theme:
  name: material
  palette: 
  - scheme: slate 
    primary: red
    accent: red
  features:
    - navigation.tabs
    - search.suggest
    - content.code.copy
    - navigation.instant
    - navigation.tracking
    - toc.follow

plugins:
  - search

extra_css:
  - stylesheets/extra.css
